@startuml
package "Ressourcix" {
    object main
    object idManager
    class Jahresplan


    package "Personalverwaltung"{
        object mitarbeiterverwaltung
        enum Schweregrad
        enum Rolle
        class Mitarbeiter
        class Qualifikation



    }

    package "PersonalFerien"{
        enum FerienStatus
        enum FerienArt
        class FerienEintrag
        class WochenBereich

    }

}

@enduml