@startuml Ressourcix_Package_Diagram
' ===== PACKAGE GROUPING =====
package "ressourcix.app" {
    class App
}

package "ressourcix.domain" {
    class Employee
    class EmployeeManagement
    class VacationEntry
    class WeekRange
    class VacationPlanner
    enum Role
    enum VacationStatus
}

package "ressourcix.calendar" {
    interface CalendarOutput
    class ConsoleCalendarOutput
}

package "ressourcix.gui" {
    class GuiBorderPane
}

package "ressourcix.ui" {
    class ConsoleIO
    enum MessageType
    interface UserInterface
}

package "ressourcix.ui.menu" {
    class MainMenu
}

package "ressourcix.util" {
    class IdProvider
}

package "root" {
    interface Graphical
    class Main
}

@enduml